# Generated by Django 4.1.5 on 2023-02-13 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pontoturistico_picture'),
        ('localization', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Addresss',
            new_name='Address',
        ),
    ]
