# Generated by Django 4.1.5 on 2023-01-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentreviews', '0001_initial'),
        ('core', '0003_pontoturistico_attractions'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='comment',
            field=models.ManyToManyField(to='commentreviews.comment'),
        ),
    ]
