# Generated by Django 4.1.5 on 2023-01-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('core', '0004_pontoturistico_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='comment',
            field=models.ManyToManyField(to='reviews.reviewscomment'),
        ),
    ]
