# Generated by Django 4.1.5 on 2023-01-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_reviewscomment_score'),
        ('commentreviews', '0001_initial'),
        ('core', '0005_alter_pontoturistico_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='reviews',
            field=models.ManyToManyField(to='reviews.reviewscomment'),
        ),
        migrations.AlterField(
            model_name='pontoturistico',
            name='comment',
            field=models.ManyToManyField(to='commentreviews.comment'),
        ),
    ]
