# Generated by Django 4.1.5 on 2023-01-30 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0001_initial'),
        ('core', '0006_pontoturistico_reviews_alter_pontoturistico_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='Address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='localization.addresss'),
            preserve_default=False,
        ),
    ]
