# Generated by Django 4.1.5 on 2023-02-06 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localization', '0001_initial'),
        ('core', '0007_pontoturistico_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='Address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localization.addresss'),
        ),
    ]
