# Generated by Django 4.1.5 on 2023-02-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_pontoturistico_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pontos_turisticos'),
        ),
    ]
