# Generated by Django 4.1.5 on 2023-01-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewscomment',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
