# Generated by Django 4.1.5 on 2023-02-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractions',
            name='minimun_age',
            field=models.IntegerField(),
        ),
    ]
